apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
      annotations:
{{- if .Values.annotations.disable -}}
        dapr.io/enabled: "true"
        dapr.io/app-id: "pub"
        dapr.io/app-port: "8080"
{{- end -}}
    spec:
      containers:
      - name: pub
        image: matheuscruzdev/pub:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pub
spec:
  selector:
    app: pub
  ports:
  - port: 8080
    targetPort: 8080