apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      annotations:
{{- if .Values.annotations.disable -}}
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{ .Values.appName }}"
        dapr.io/app-port: "8080"
{{- end -}}
    spec:
      containers:
      - name: "{{ .Values.appName }}"
        image: matheuscruzdev/{{ .Values.appName }}:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: 8080
    targetPort: 8080