apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub
  template:
    metadata:
      labels:
        app: sub
      annotations:
        dapr.io/app-id: "sub"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: "sub"
        image: matheuscruzdev/sub:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sub
spec:
  selector:
    app: sub
  ports:
  - port: 8080
    targetPort: 8080