apiVersion: apps/v1
kind: Deployment
metadata:
  name: script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: script
  template:
    metadata:
      labels:
        app: script
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: script
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: script
        image: matheuscruzdev/script:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: script
spec:
  selector:
    app: script
  ports:
  - port: 8080
    targetPort: 8080